

export const SHOW_GPS_ERROR = 'SHOW_GPS_ERROR';
export const SHOW_ORIENTATION_ERROR = 'SHOW_ORIENTATION_ERROR';

export const GEOLOCATE = 'GEOLOCATE';
export const FINISH_STARTUP = 'FINISH_STARTUP';
export const FINISH_ZOOM = 'FINISH_ZOOM';

export const START_XRAY = 'START_XRAY';
export const TRACE_XRAY_CENTER = 'TRACE_XRAY_CENTER';

export const TOGGLE_NAV = 'TOGGLE_NAV';
