

export const START_XRAY = 'START_XRAY';
export const TRACE_XRAY_CENTER = 'TRACE_XRAY_CENTER';

export const SHOW_GPS_ERROR = 'SHOW_GPS_ERROR';
export const SHOW_ORIENTATION_ERROR = 'SHOW_ORIENTATION_ERROR';
