

export const SHOW_GPS_ERROR = 'SHOW_GPS_ERROR';
export const SHOW_ORIENTATION_ERROR = 'SHOW_ORIENTATION_ERROR';

export const GEOLOCATE = 'GEOLOCATE';
export const FINISH_STARTUP = 'FINISH_STARTUP';
export const FINISH_ZOOM = 'FINISH_ZOOM';

export const START_XRAY = 'START_XRAY';
export const TRACE_XRAY_CENTER = 'TRACE_XRAY_CENTER';
export const ZOOM_XRAY = 'ZOOM_XRAY';
export const START_CALIBRATION = 'START_CALIBRATION';
export const END_CALIBRATION = 'END_CALIBRATION';

export const TOGGLE_NAV = 'TOGGLE_NAV';
